artifact_location: /Users/seonghoonjeong/Desktop/School/Graduate project/project/GASBY/GASBY-homography/runs/mlflow/401146409442387706
creation_time: 1719724062120
experiment_id: '401146409442387706'
last_update_time: 1719724062120
lifecycle_stage: active
name: /Shared/YOLOv8
