artifact_uri: /Users/seonghoonjeong/Desktop/School/Graduate project/project/GASBY/GASBY-homography/runs/mlflow/401146409442387706/993d3b38174d4ca5bac151969b529edb/artifacts
end_time: 1719735089633
entry_point_name: ''
experiment_id: '401146409442387706'
lifecycle_stage: active
run_id: 993d3b38174d4ca5bac151969b529edb
run_name: custom_yolov8_model5
run_uuid: 993d3b38174d4ca5bac151969b529edb
source_name: ''
source_type: 4
source_version: ''
start_time: 1719735054389
status: 3
tags: []
user_id: seonghoonjeong
