artifact_uri: /Users/seonghoonjeong/Desktop/School/Graduate project/project/GASBY/GASBY-homography/runs/mlflow/401146409442387706/1aaed79ab84e4fde95ab64e10b8eb7a0/artifacts
end_time: 1719724070952
entry_point_name: ''
experiment_id: '401146409442387706'
lifecycle_stage: active
run_id: 1aaed79ab84e4fde95ab64e10b8eb7a0
run_name: custom_yolov8_model2
run_uuid: 1aaed79ab84e4fde95ab64e10b8eb7a0
source_name: ''
source_type: 4
source_version: ''
start_time: 1719724062830
status: 3
tags: []
user_id: seonghoonjeong
